version: '3.4'

services:
  buddhabrot.api:
    image: ${DOCKER_REGISTRY-}buddhabrotapi
    build:
      context: .
      dockerfile: Buddhabrot/Dockerfile
    depends_on:
     - "seq"
     - "mssql"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8080:80"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=$MSSQL_SA_PWD
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"